export default [
    {
        id: 1,
        image: 'img/gray-sneaker-big.png',
        title: 'Slick formal sneaker shoe',
        priceNew: 2999,
        priceOld: 4999,
        button: '',
        isBig: true,
        status: 'hot',
    },
    {
        id: 2,
        image: 'img/peach-sneaker.png',
        title: 'Slick sneaker shoe',
        priceNew: 2999,
        priceOld: 3999,
        button: '',
        isBig: false,
        status: 'new',
    },
    {
        id: 3,
        image: 'img/brown-sneaker.png',
        title: 'Slick canvas shoe',
        priceNew: 2999,
        priceOld: 3999,
        button: '',
        isBig: false,
        status: '',
    },
]